#!/bin/bash
echo "🔥 SHAME TO FLAME - DIRECT DEPLOYMENT"
echo "======================================"
echo ""
echo "Option 1: Deploy to Netlify"
echo "---------------------------"
echo "npm install -g netlify-cli"
echo "netlify deploy --dir=out --prod"
echo ""
echo "Option 2: Deploy to Vercel"
echo "--------------------------"
echo "npm install -g vercel"
echo "vercel --prod"
echo ""
echo "Your 'out' folder contains the complete website:"
ls -1 out/*.html
echo ""
echo "Total files ready: $(find out -type f | wc -l)"
echo "Total size: $(du -sh out | cut -f1)"
